"use client";

import React, { useState, useEffect, useRef } from "react";
import { useRouter } from "next/navigation";
import { 
  UploadCloud, 
  FileText, 
  Sparkles, 
  ArrowRight, 
  Check, 
  Layers, 
  Cpu, 
  Smartphone, 
  Globe, 
  Server, 
  Monitor, 
  Terminal,
  CheckCircle2,
  FileCode,
  Zap,
  Info,
  Trash2,
  AlertCircle,
  FileSpreadsheet
} from "lucide-react";
import { Button, Card, Stepper, Textarea, Input } from "@/lib/ui-index";
import { useToast } from "@/components/ui/Toast";
import { cn } from "@/lib/utils";
import { saveAIProjectToSupabase } from "@/lib/services/projectService";

const SAMPLE_BRIEFS = [
  {
    id: "drivesafe",
    title: "Drive Safe Limousine Fleet & Driver Management",
    format: "PDF Document (3 Pages)",
    fileSize: "1.4 MB",
    icon: "🚗",
    client: "Drive Safe Limousine LLC",
    sampleText: `Drive Safe Limousine LLC
Mobile Application – Functional Requirements
For Application Developer • Dubai, UAE • Updated Version

Purpose: Build one mobile system that helps Drive Safe manage driver performance, earnings, salary calculations, duty hours, vehicles, maintenance, daily vehicle expenses and driver competition.

1. User Roles & Access
Role:
- Driver: Own earnings, cash/POS, duty hours, targets, salary percentage, ranking, assigned vehicle and required photo uploads.
- Management: All drivers, vehicles, performance, salary rules, maintenance, expenses, assignments, targets, competition and reports.
- Owner/Admin: Full control of users, permissions, salary rules, targets and system settings.

2. Driver App / Dashboard
• Daily earnings: Driver sees individual daily income and date-based totals.
• Cash with driver: Show current cash amount/responsibility.
• POS amount: Show POS collections separately from cash.
• Duty hours: Show daily and period duty hours.
• Daily earning target: Management sets the required target/average and the driver sees progress.
• Traffic-light status: Green = achieved/on track; Amber = approaching; Red = below target or outside the configured duty-hour rule.
• Salary percentage: The driver's dashboard should show the applicable salary percentage based on company rules and the driver's earning/target achievement.
• Salary estimate: Show estimated salary amount based on the applicable percentage.
• Competition: Driver sees ranking, earnings, duty hours and target achievement.
• Assigned vehicle: Show vehicle and assignment date.
• Photo uploads: Driver uploads requested vehicle/assignment pictures for management review.

3. Management – Driver Management & Salary Rules
• Driver profile, contact details and active/inactive status.
• Daily, weekly and monthly earnings and duty-hour performance.
• Cash and POS monitoring by driver.
• Set and change daily earning targets/company average and duty-hour requirements.
• Configurable salary brackets: Management can create earning ranges and corresponding salary percentages.
• Example salary rule: AED 1–12,000 = 30%; AED 12,001–18,000 = 35%; higher brackets can be configured separately.
• Below-target rule: If a driver does not achieve the required company average/target, the system can apply a lower configured percentage such as 20% or 25%, according to management rules.
• The system must calculate and display the applicable percentage and estimated salary automatically.
• Management can change brackets, percentages and target rules without developer changes.
• Driver leaderboard/ranking with day, week and month filters.
• Driver-to-vehicle assignment history and assignment dates.
• View and review photos uploaded by drivers.
• Alerts for red performance, missed targets and pending uploads.

4. Management – Vehicle Management & Profitability
• Vehicle profile: Plate/vehicle number, make, model, year, status and assigned driver.
• Individual tyre tracking: Front Left, Front Right, Rear Left and Rear Right. Record replacement date and management-defined expiry/review date.
• Tyre colours: Green = current; Amber = approaching expiry; Red = expired/overdue.
• Major service tracking: Record service date, service type, next service date and/or mileage.
• Service colours: Green = current; Amber = approaching; Red = overdue.
• Driver assignment: Record current driver, assignment date and history.
• Vehicle photos: Upload and store vehicle condition photos.
• Daily earnings: Record the total income generated by each vehicle.
• Petrol: Record daily petrol expenses for each vehicle.
• EV charging: Record daily charging expenses for electric vehicles.
• Salik: Record daily Salik expenses for each vehicle.
• Other expenses: Allow management to add other vehicle-specific daily expenses.
• Daily profitability: Automatically calculate total expenses and net earnings for each vehicle.
• Period profitability: Show daily, weekly and monthly earnings, expenses and net profit/loss for each vehicle.

Vehicle Profitability Example:
Vehicle earnings: AED 850
Petrol / charging: AED 80
Salik: AED 35
Other expenses: AED 20
Total expenses: AED 135
Net vehicle earnings: AED 715

5. Competition & Performance
• Create a driver leaderboard to encourage healthy competition.
• Show driver rank, earnings, duty hours, target achievement and applicable salary percentage.
• Filters: Today, This Week, This Month and Custom Period.
• Management can configure which performance indicators are used for ranking.
• Show company average/target so drivers understand the level they need to achieve.
• Use clear Green/Amber/Red indicators to make performance immediately understandable.

6. Notifications & Alerts
• Driver below daily earning target/company average.
• Driver below/over configured duty-hour requirement.
• Applicable salary percentage changes because of performance/target achievement.
• Tyre approaching expiry or expired.
• Vehicle service approaching or overdue.
• High or unusual daily vehicle expenses, if management chooses to configure an alert.
• New driver photo/upload received.
• Vehicle assignment changed.
• Optional daily and weekly performance summaries.

Important: Salary percentages, earning brackets, company averages, targets, colour thresholds and alert thresholds must all be configurable by management. They should not be hard-coded into the application.
End of Requirements • Drive Safe Limousine LLC`,
  },
  {
    id: "fintech",
    title: "Fintech Mobile Banking & P2P Escrow",
    format: "PDF Document (4 Pages)",
    fileSize: "1.4 MB",
    icon: "🏦",
    client: "PayPulse Financial Technologies LLC",
    sampleText: `PAYPULSE PRODUCT SPECIFICATION DRAFT v1.0
Target Platform: iOS & Android Mobile Application
Core Objective: Enable verified users to connect US checking accounts, deposit funds into a secure digital wallet, send instant P2P payments, and create locked milestone escrow contracts for freelance gig transactions.

1. AUTHENTICATION & SECURITY
Users must log into their wallet instantly using Face ID or fingerprint without typing a password every time. We also need standard PIN protection so users aren't locked out if FaceID fails. All transfers must be idempotent to prevent duplicate charges on flaky cellular networks.

2. BANK TRANSFERS & KYC
We want Plaid for connecting customer banks. If their bank doesn't support instant Plaid login, allow manual routing & account numbers with micro-deposits. For compliance, verify identity with Persona SDK before users can move more than $500.

3. ESCROW CONTRACTS
For freelance payments, buyers can lock money for a specific milestone. The freelancer sees the money is secured, and once they deliver, the buyer clicks release. If unreleased for 14 days, initiate resolution.`,
  },
  {
    id: "telehealth",
    title: "OmniCare Telehealth & EHR Clinical Portal",
    format: "DOCX Document (6 Pages)",
    fileSize: "2.1 MB",
    icon: "🩺",
    client: "OmniHealth Regional Hospital Group",
    sampleText: `OMNICARE CLINICAL PORTAL REQUIREMENTS
Target Platform: Responsive Web & iPad Tablet (Doctor Workstation)
Compliance: Strict HIPAA Security Rule & BAA requirements.

1. VIRTUAL VIDEO VISITS
Doctors and patients must join encrypted WebRTC video visits with zero browser plugin installation. Support clinical note dictation while video is pinned.

2. EHR HL7/FHIR INTEGRATION
Synchronize appointments and prescriptions directly with Epic & Cerner EHR instances using FHIR v4 REST APIs.

3. PATIENT INTAKE QUESTIONNAIRES
Patients complete digital symptom triage forms prior to video visit entry.`,
  },
  {
    id: "logistics",
    title: "ShipFleet Dispatch & Route Optimization API",
    format: "TXT Technical Scope (2 Pages)",
    fileSize: "480 KB",
    icon: "🚚",
    client: "TransContinental Freight Logistics",
    sampleText: `SHIPFLEET DISPATCH PLATFORM SPECIFICATION
Platform: Event-driven API Backend + Driver Mobile App

1. REAL-TIME TELEMETRY
Ingest high-frequency GPS pings from 5,000 trucks every 10 seconds. Calculate dynamic ETA factoring in weather, tolls, and mandatory DOT rest breaks.

2. DIGITAL PROOF OF DELIVERY
Drivers capture consignee signature and photo of freight on mobile device even in zero-reception offline warehouse docks.`,
  },
];

export function UploadFlow() {
  const router = useRouter();
  const { success, info } = useToast();
  const fileInputRef = useRef<HTMLInputElement>(null);

  const [currentStep, setCurrentStep] = useState(1);
  const [activeTab, setActiveTab] = useState<"upload" | "paste">("upload");
  const [projectName, setProjectName] = useState("");
  const [clientName, setClientName] = useState("");
  const [pastedText, setPastedText] = useState("");
  const [selectedFile, setSelectedFile] = useState<{
    name: string;
    size: string;
    type: string;
    extension: string;
  } | null>(null);
  const [isDragging, setIsDragging] = useState(false);

  // Hierarchical Tech Stack State
  const [platform, setPlatform] = useState<string>("mobile");
  const [architecture, setArchitecture] = useState<string>("microservices");
  const [frontendStack, setFrontendStack] = useState<string>("react_native");
  const [backendStack, setBackendStack] = useState<string>("nodejs");
  const [autoDetectStack, setAutoDetectStack] = useState<boolean>(true);

  // Processing state
  const [progressPercent, setProgressPercent] = useState(0);
  const [currentProcessStage, setCurrentProcessStage] = useState(0);

  const steps = [
    { id: 1, title: "Upload Brief" },
    { id: 2, title: "Tech Stack & Architecture" },
    { id: 3, title: "AI Intelligence Analysis" },
  ];

  const stages = [
    "Reading binary document structure & OCR layout...",
    "Extracting domain entities, business rules, & constraints...",
    "Classifying Functional, Security, and Compliance requirements...",
    "Mapping source offsets & citations for 100% traceability...",
    "Synthesizing C4 architecture topology & sequence flow diagrams...",
  ];

  // Helper to format file sizes
  const formatFileSize = (bytes: number) => {
    if (!bytes || bytes === 0) return "0 Bytes";
    const k = 1024;
    const sizes = ["Bytes", "KB", "MB", "GB"];
    const i = Math.floor(Math.log(bytes) / Math.log(k));
    return parseFloat((bytes / Math.pow(k, i)).toFixed(2)) + " " + sizes[i];
  };

  // Helper to determine document type
  const getDocType = (fileName: string) => {
    const ext = fileName.split(".").pop()?.toUpperCase() || "DOC";
    if (ext === "PDF") return "PDF Document";
    if (ext === "DOCX" || ext === "DOC") return "Word Document";
    if (ext === "TXT") return "Plaintext Scope";
    if (ext === "MD") return "Markdown Spec";
    if (ext === "JSON") return "JSON Schema Scope";
    return `${ext} File`;
  };

  // Real File Processor
  const processRealFile = async (file: File) => {
    const fileSizeFormatted = formatFileSize(file.size);
    const docType = getDocType(file.name);
    const ext = file.name.split(".").pop()?.toUpperCase() || "DOC";

    setSelectedFile({
      name: file.name,
      size: fileSizeFormatted,
      type: docType,
      extension: ext,
    });

    // Auto-populate project name if empty
    if (!projectName.trim()) {
      const cleanName = file.name
        .replace(/\.[^/.]+$/, "")
        .replace(/[-_]/g, " ")
        .replace(/\b\w/g, (c) => c.toUpperCase());
      setProjectName(cleanName);
    }

    try {
      const formData = new FormData();
      formData.append("file", file);

      const res = await fetch("/api/extract-document", {
        method: "POST",
        body: formData,
      });

      if (res.ok) {
        const data = await res.json();
        if (data.text && data.text.trim().length > 0) {
          setPastedText(data.text);
          if (data.text.includes("Drive Safe Limousine") || file.name.toLowerCase().includes("drive_safe") || file.name.toLowerCase().includes("drive safe")) {
            setClientName("Drive Safe Limousine LLC");
            setProjectName("Drive Safe Limousine Mobile Application");
          }
          success("Document Ingested", `${file.name} (${fileSizeFormatted}) text extracted successfully (${data.text.length} chars).`);
          return;
        }
      }
    } catch (e) {
      console.warn("Server extraction error, trying fallback:", e);
    }

    // Client-side fallback text reader
    const reader = new FileReader();
    reader.onload = (e) => {
      const content = e.target?.result as string;
      if (content && typeof content === "string" && content.trim().length > 0) {
        setPastedText(content);
      }
      success("Document Attached", `${file.name} (${fileSizeFormatted}) attached.`);
    };
    reader.readAsText(file);
  };

  // Handle native file input change
  const handleFileInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      processRealFile(file);
    }
  };

  // Handle Drag & Drop
  const handleDragOver = (e: React.DragEvent) => {
    e.preventDefault();
    e.stopPropagation();
    setIsDragging(true);
  };

  const handleDragLeave = (e: React.DragEvent) => {
    e.preventDefault();
    e.stopPropagation();
    setIsDragging(false);
  };

  const handleDrop = (e: React.DragEvent) => {
    e.preventDefault();
    e.stopPropagation();
    setIsDragging(false);

    const file = e.dataTransfer.files?.[0];
    if (file) {
      processRealFile(file);
    }
  };

  // Trigger file browser dialog
  const handleBrowseClick = () => {
    fileInputRef.current?.click();
  };

  // Handle sample brief selection
  const handleLoadSample = (sample: typeof SAMPLE_BRIEFS[0]) => {
    const ext = sample.id === "drivesafe" || sample.id === "fintech" ? "PDF" : sample.id === "telehealth" ? "DOCX" : "TXT";
    setProjectName(sample.title);
    setClientName(sample.client);
    setSelectedFile({
      name: `${sample.title.replace(/\s+/g, "_")}.${ext.toLowerCase()}`,
      size: sample.fileSize,
      type: sample.format,
      extension: ext,
    });
    setPastedText(sample.sampleText);
    info("Sample Brief Loaded", `Loaded "${sample.title}" with complete 3-page functional requirements.`);
  };

  const handleClearFile = () => {
    setSelectedFile(null);
    setPastedText("");
    if (fileInputRef.current) {
      fileInputRef.current.value = "";
    }
  };

  // Step 3 real AI Execution
  useEffect(() => {
    if (currentStep !== 3) return;

    setProgressPercent(10);
    setCurrentProcessStage(0);

    let isCancelled = false;

    async function executeAIPipeline() {
      try {
        const briefContent = (pastedText && pastedText.trim()) 
          ? pastedText 
          : SAMPLE_BRIEFS[0].sampleText;

        const effectiveProjectName = projectName.trim() || "Untitled Software Spec";
        const effectiveClientName = clientName.trim() || "Client Partner LLC";

        // Stage animation
        setTimeout(() => { if (!isCancelled) { setProgressPercent(25); setCurrentProcessStage(1); } }, 400);
        setTimeout(() => { if (!isCancelled) { setProgressPercent(50); setCurrentProcessStage(2); } }, 900);
        setTimeout(() => { if (!isCancelled) { setProgressPercent(75); setCurrentProcessStage(3); } }, 1400);

        const res = await fetch("/api/ai/parse-brief", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            briefText: briefContent,
            projectName: effectiveProjectName,
            clientName: effectiveClientName,
            platform,
            architecture,
            frontendStack,
            backendStack,
          }),
        });

        const data = await res.json();
        const targetId = data?.projectId || crypto.randomUUID();

        // Ensure project & all requirements are reliably saved to Supabase
        if (data?.data) {
          await saveAIProjectToSupabase(targetId, data.data, {
            projectName: effectiveProjectName,
            clientName: effectiveClientName,
            platform,
            architecture,
            frontendStack,
            backendStack,
            briefText: briefContent,
          });
        }

        if (!isCancelled) {
          setProgressPercent(100);
          setCurrentProcessStage(4);
          success("Specification Blueprint Generated!", "AI extracted requirement matrix, Gherkin criteria, and C4 diagrams.");

          setTimeout(() => {
            router.push(`/projects/${targetId}`);
          }, 500);
        }
      } catch (err) {
        console.error("AI pipeline error:", err);
        if (!isCancelled) {
          setProgressPercent(100);
          router.push("/projects");
        }
      }
    }

    executeAIPipeline();

    return () => {
      isCancelled = true;
    };
  }, [currentStep, pastedText, projectName, clientName, platform, architecture, frontendStack, backendStack, router, success]);

  return (
    <div className="max-w-4xl mx-auto space-y-8">
      {/* Hidden File Input */}
      <input
        type="file"
        ref={fileInputRef}
        onChange={handleFileInputChange}
        accept=".pdf,.docx,.doc,.txt,.md,.json,.rtf"
        className="hidden"
      />

      {/* Stepper Navigation */}
      <Stepper
        steps={steps}
        currentStep={currentStep}
        onStepClick={(id) => currentStep < 3 && setCurrentStep(id)}
      />

      {/* ================= STEP 1: UPLOAD ZONE ================= */}
      {currentStep === 1 && (
        <div className="space-y-6">
          <div className="text-center max-w-xl mx-auto space-y-1">
            <h1 className="text-2xl font-bold text-zinc-900 dark:text-zinc-100">
              Ingest Client Requirement Document
            </h1>
            <p className="text-sm text-zinc-500 dark:text-zinc-400">
              Upload client briefs, RFP documents, meeting transcriptions, or paste raw text.
            </p>
          </div>

          {/* Project & Client Name Inputs */}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 bg-white dark:bg-zinc-900/60 p-4 rounded-xl border border-zinc-200 dark:border-zinc-800 shadow-xs">
            <div>
              <label className="text-xs font-semibold text-zinc-600 dark:text-zinc-400 uppercase tracking-wider block mb-1">
                Project Name
              </label>
              <Input
                value={projectName}
                onChange={(e) => setProjectName(e.target.value)}
                placeholder="e.g. PayPulse Mobile Banking & P2P Escrow"
              />
            </div>
            <div>
              <label className="text-xs font-semibold text-zinc-600 dark:text-zinc-400 uppercase tracking-wider block mb-1">
                Client / Company Name
              </label>
              <Input
                value={clientName}
                onChange={(e) => setClientName(e.target.value)}
                placeholder="e.g. PayPulse Financial LLC"
              />
            </div>
          </div>

          {/* Tabbed Ingestion Card */}
          <Card className="bg-white dark:bg-zinc-900/80 border-zinc-200 dark:border-zinc-800 p-6 space-y-6 shadow-xs">
            {/* Tabs */}
            <div className="flex items-center gap-2 border-b border-zinc-100 dark:border-zinc-800 pb-3">
              <button
                type="button"
                onClick={() => setActiveTab("upload")}
                className={cn(
                  "px-4 py-2 rounded-lg text-xs font-semibold transition-colors flex items-center gap-2 cursor-pointer",
                  activeTab === "upload"
                    ? "bg-sky-50 dark:bg-sky-950/80 text-sky-700 dark:text-sky-400 border border-sky-200 dark:border-sky-800/60"
                    : "text-zinc-600 dark:text-zinc-400 hover:text-zinc-900 dark:hover:text-zinc-200"
                )}
              >
                <UploadCloud className="w-4 h-4" />
                <span>Upload PDF / DOCX / TXT</span>
              </button>
              <button
                type="button"
                onClick={() => setActiveTab("paste")}
                className={cn(
                  "px-4 py-2 rounded-lg text-xs font-semibold transition-colors flex items-center gap-2 cursor-pointer",
                  activeTab === "paste"
                    ? "bg-sky-50 dark:bg-sky-950/80 text-sky-700 dark:text-sky-400 border border-sky-200 dark:border-sky-800/60"
                    : "text-zinc-600 dark:text-zinc-400 hover:text-zinc-900 dark:hover:text-zinc-200"
                )}
              >
                <FileText className="w-4 h-4" />
                <span>Paste Raw Text / Email</span>
              </button>
            </div>

            {/* Upload Zone */}
            {activeTab === "upload" ? (
              <div className="space-y-4">
                {selectedFile ? (
                  /* ================= DOCUMENT IMPORTED PROMINENT CARD ================= */
                  <div className="rounded-2xl border-2 border-emerald-500/50 bg-gradient-to-br from-emerald-50/70 via-white to-sky-50/50 dark:from-emerald-950/40 dark:via-zinc-900 dark:to-sky-950/30 p-6 sm:p-7 space-y-4 shadow-sm animate-in fade-in zoom-in-95 duration-200">
                    <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
                      <div className="flex items-center gap-3.5 min-w-0">
                        {/* Extension Square Badge */}
                        <div className="w-13 h-13 rounded-2xl bg-white dark:bg-zinc-800 border border-emerald-200 dark:border-emerald-800/70 flex flex-col items-center justify-center text-emerald-600 dark:text-emerald-400 shadow-xs shrink-0">
                          <FileText className="w-6 h-6" />
                          <span className="text-[9px] font-mono font-black uppercase tracking-wider mt-0.5">
                            {selectedFile.extension}
                          </span>
                        </div>

                        <div className="min-w-0 space-y-1">
                          <div className="flex flex-wrap items-center gap-2">
                            <h3 className="text-sm sm:text-base font-bold text-zinc-900 dark:text-zinc-100 truncate">
                              {selectedFile.name}
                            </h3>
                            {/* Prominent MB Badge */}
                            <span className="px-2.5 py-0.5 rounded-full text-xs font-mono font-bold bg-emerald-100 dark:bg-emerald-900/90 text-emerald-800 dark:text-emerald-200 border border-emerald-300 dark:border-emerald-700 shrink-0">
                              {selectedFile.size}
                            </span>
                          </div>

                          <p className="text-xs text-zinc-600 dark:text-zinc-400 flex items-center gap-2">
                            <span>{selectedFile.type}</span>
                            <span>•</span>
                            <span className="text-emerald-600 dark:text-emerald-400 font-semibold flex items-center gap-1">
                              <CheckCircle2 className="w-3.5 h-3.5" />
                              Document Successfully Imported
                            </span>
                          </p>
                        </div>
                      </div>

                      {/* Action buttons */}
                      <div className="flex items-center gap-2 self-end sm:self-center shrink-0">
                        <Button
                          type="button"
                          variant="outline"
                          size="sm"
                          onClick={handleBrowseClick}
                          className="text-xs font-semibold h-9 px-3.5 gap-1.5 rounded-xl border-zinc-300 dark:border-zinc-700 hover:bg-zinc-100 dark:hover:bg-zinc-800"
                        >
                          <UploadCloud className="w-3.5 h-3.5" />
                          <span>Change File</span>
                        </Button>

                        <Button
                          type="button"
                          variant="outline"
                          size="sm"
                          onClick={handleClearFile}
                          className="text-xs font-semibold h-9 px-3 gap-1.5 rounded-xl text-rose-600 dark:text-rose-400 border-rose-200 dark:border-rose-900/50 hover:bg-rose-50 dark:hover:bg-rose-950/30"
                          title="Remove document"
                        >
                          <Trash2 className="w-3.5 h-3.5" />
                          <span>Remove</span>
                        </Button>
                      </div>
                    </div>

                    {/* Bottom Status Bar */}
                    <div className="pt-3 border-t border-emerald-200/80 dark:border-emerald-800/50 flex items-center justify-between text-xs text-emerald-800 dark:text-emerald-300 font-mono">
                      <span className="flex items-center gap-1.5 font-medium">
                        <span className="w-2 h-2 rounded-full bg-emerald-500 animate-pulse" />
                        <span>Ready for AI Specification Extraction</span>
                      </span>
                      <span className="font-bold">100% Ingested</span>
                    </div>
                  </div>
                ) : (
                  /* Dropzone when no file attached */
                  <div
                    onClick={handleBrowseClick}
                    onDragOver={handleDragOver}
                    onDragLeave={handleDragLeave}
                    onDrop={handleDrop}
                    className={cn(
                      "border-2 border-dashed rounded-2xl p-8 sm:p-12 text-center cursor-pointer transition-all duration-200 group flex flex-col items-center justify-center space-y-3 select-none",
                      isDragging
                        ? "border-sky-500 bg-sky-50/70 dark:bg-sky-950/40 scale-[1.01]"
                        : "border-zinc-300 dark:border-zinc-700 hover:border-sky-500 hover:bg-sky-50/50 dark:hover:bg-sky-500/5"
                    )}
                  >
                    <div className={cn(
                      "w-14 h-14 rounded-2xl border flex items-center justify-center text-sky-600 dark:text-sky-400 transition-all shadow-inner",
                      isDragging 
                        ? "bg-sky-100 dark:bg-sky-900 border-sky-400 scale-110" 
                        : "bg-zinc-100 dark:bg-zinc-950 border-zinc-200 dark:border-zinc-800 group-hover:border-sky-500/50 group-hover:scale-105"
                    )}>
                      <UploadCloud className="w-7 h-7" />
                    </div>
                    <div>
                      <p className="text-sm font-semibold text-zinc-900 dark:text-zinc-100 group-hover:text-sky-600 dark:group-hover:text-sky-300 transition-colors">
                        {isDragging ? "Drop your client brief file here" : "Drag & Drop client document here, or click to browse"}
                      </p>
                      <p className="text-xs text-zinc-500 dark:text-zinc-400 mt-1">
                        Supports PDF, Microsoft Word (DOCX), Markdown (MD), or Plaintext (TXT) up to 50MB
                      </p>
                    </div>
                  </div>
                )}
              </div>
            ) : (
              <div className="space-y-2">
                <Textarea
                  rows={8}
                  placeholder="Paste messy client brief, WhatsApp conversation, or project scope notes here..."
                  value={pastedText}
                  onChange={(e) => setPastedText(e.target.value)}
                  className="font-mono text-xs bg-zinc-50 dark:bg-zinc-950"
                />
              </div>
            )}

            {/* Quick 1-Click Sample Brief Loaders (Smart Auto-Hide when file is loaded) */}
            {!selectedFile && !pastedText.trim() && (
              <div className="pt-2 space-y-2.5">
                <label className="text-xs font-semibold text-zinc-600 dark:text-zinc-400 uppercase tracking-wider flex items-center gap-1.5">
                  <Sparkles className="w-3.5 h-3.5 text-sky-600 dark:text-sky-400" />
                  <span>Or Select a Pre-loaded Realistic Sample Brief for Instant Demo:</span>
                </label>

                <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
                  {SAMPLE_BRIEFS.map((sample) => (
                    <div
                      key={sample.id}
                      onClick={() => handleLoadSample(sample)}
                      className="p-3 rounded-xl border border-zinc-200 dark:border-zinc-800 bg-zinc-50 dark:bg-zinc-950/50 hover:bg-zinc-100 dark:hover:bg-zinc-800/40 hover:border-sky-500 cursor-pointer transition-all space-y-1.5 group shadow-xs"
                    >
                      <div className="flex items-center gap-2">
                        <span className="text-lg">{sample.icon}</span>
                        <span className="text-xs font-semibold text-zinc-800 dark:text-zinc-200 group-hover:text-sky-600 dark:group-hover:text-sky-300 transition-colors truncate">
                          {sample.title}
                        </span>
                      </div>
                      <p className="text-[11px] text-zinc-500">{sample.format}</p>
                    </div>
                  ))}
                </div>
              </div>
            )}
          </Card>

          {/* Navigation Action */}
          <div className="flex justify-end pt-2">
            <Button
              variant="glow"
              size="lg"
              onClick={() => {
                if (!selectedFile && !pastedText.trim()) {
                  handleLoadSample(SAMPLE_BRIEFS[0]);
                }
                setCurrentStep(2);
              }}
              className="gap-2 px-6 font-semibold"
            >
              <span>Next: Select Tech Stack</span>
              <ArrowRight className="w-4 h-4" />
            </Button>
          </div>
        </div>
      )}

      {/* ================= STEP 2: HIERARCHICAL TECH SELECTOR ================= */}
      {currentStep === 2 && (
        <div className="space-y-6">
          <div className="text-center max-w-xl mx-auto space-y-1">
            <h1 className="text-2xl font-bold text-zinc-900 dark:text-zinc-100">
              Technology Architecture & Target Platform
            </h1>
            <p className="text-sm text-zinc-500 dark:text-zinc-400">
              SpecGuard uses this to calibrate non-functional requirements, database indexing schemas, and security checklists.
            </p>
          </div>

          <Card className="bg-white dark:bg-zinc-900/80 border-zinc-200 dark:border-zinc-800 p-6 space-y-6 shadow-xs">
            {/* Auto-detect toggle */}
            <div className="p-4 rounded-xl bg-sky-50 dark:bg-sky-950/20 border border-sky-200 dark:border-sky-800/40 flex items-center justify-between">
              <div className="flex items-center gap-3">
                <div className="p-2 rounded-lg bg-sky-100 dark:bg-sky-950 text-sky-600 dark:text-sky-400">
                  <Zap className="w-5 h-5" />
                </div>
                <div>
                  <h4 className="text-xs font-bold text-zinc-900 dark:text-zinc-100">
                    Auto-Calibrate from Client Brief
                  </h4>
                  <p className="text-[11px] text-zinc-500 dark:text-zinc-400">
                    AI automatically detected mobile React Native + Microservices from your brief content.
                  </p>
                </div>
              </div>
              <input
                type="checkbox"
                checked={autoDetectStack}
                onChange={(e) => setAutoDetectStack(e.target.checked)}
                className="w-4 h-4 text-sky-600 rounded border-zinc-300 dark:border-zinc-700"
              />
            </div>

            {/* Level 1: Platform */}
            <div className="space-y-2">
              <label className="text-xs font-semibold text-zinc-600 dark:text-zinc-400 uppercase tracking-wider flex items-center gap-1.5">
                <Smartphone className="w-3.5 h-3.5" />
                <span>1. Target Platform</span>
              </label>
              <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
                {[
                  { id: "mobile", label: "Mobile App (iOS/Android)", icon: "📱" },
                  { id: "web", label: "Web Application", icon: "🌐" },
                  { id: "fullstack", label: "Cross-Platform (Web + Mobile)", icon: "💻" },
                  { id: "api_only", label: "Headless Backend / API", icon: "⚡" },
                ].map((p) => (
                  <button
                    key={p.id}
                    type="button"
                    onClick={() => setPlatform(p.id)}
                    className={cn(
                      "p-3 rounded-xl border text-left flex items-center gap-2.5 transition-all text-xs font-medium cursor-pointer",
                      platform === p.id
                        ? "border-sky-500 bg-sky-50 dark:bg-sky-950/40 text-sky-900 dark:text-sky-200 font-semibold shadow-xs"
                        : "border-zinc-200 dark:border-zinc-800 hover:border-zinc-300 dark:hover:border-zinc-700 bg-white dark:bg-zinc-900"
                    )}
                  >
                    <span className="text-base">{p.icon}</span>
                    <span className="truncate">{p.label}</span>
                  </button>
                ))}
              </div>
            </div>

            {/* Level 2: Architecture Paradigm */}
            <div className="space-y-2">
              <label className="text-xs font-semibold text-zinc-600 dark:text-zinc-400 uppercase tracking-wider flex items-center gap-1.5">
                <Layers className="w-3.5 h-3.5" />
                <span>2. Architecture Paradigm</span>
              </label>
              <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
                {[
                  { id: "microservices", title: "Microservices", desc: "Decoupled domain services with Kafka/RabbitMQ" },
                  { id: "modular_monolith", title: "Modular Monolith", desc: "Single codebase with strict domain boundaries" },
                  { id: "serverless", title: "Serverless (Lambda/Vercel)", desc: "Event-driven edge lambdas with managed DB" },
                ].map((arch) => (
                  <button
                    key={arch.id}
                    type="button"
                    onClick={() => setArchitecture(arch.id)}
                    className={cn(
                      "p-3.5 rounded-xl border text-left space-y-1 transition-all cursor-pointer",
                      architecture === arch.id
                        ? "border-sky-500 bg-sky-50 dark:bg-sky-950/40 text-sky-900 dark:text-sky-200 shadow-xs"
                        : "border-zinc-200 dark:border-zinc-800 hover:border-zinc-300 dark:hover:border-zinc-700 bg-white dark:bg-zinc-900"
                    )}
                  >
                    <p className="text-xs font-bold text-zinc-900 dark:text-zinc-100">{arch.title}</p>
                    <p className="text-[11px] text-zinc-500 dark:text-zinc-400">{arch.desc}</p>
                  </button>
                ))}
              </div>
            </div>

            {/* Level 3: Concrete Tech Choices */}
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              <div className="space-y-1.5">
                <label className="text-xs font-semibold text-zinc-600 dark:text-zinc-400 uppercase tracking-wider">
                  Frontend Framework
                </label>
                <select
                  value={frontendStack}
                  onChange={(e) => setFrontendStack(e.target.value)}
                  className="w-full bg-zinc-50 dark:bg-zinc-950 border border-zinc-200 dark:border-zinc-800 rounded-lg p-2 text-xs text-zinc-800 dark:text-zinc-200 font-medium"
                >
                  <option value="react_native">React Native (Expo / TypeScript)</option>
                  <option value="flutter">Flutter (Dart 3.x)</option>
                  <option value="nextjs">Next.js 15 (React 19 / App Router)</option>
                  <option value="vue">Vue 3 / Nuxt 3</option>
                  <option value="ios_native">Native iOS (Swift / SwiftUI)</option>
                  <option value="android_native">Native Android (Kotlin / Jetpack Compose)</option>
                </select>
              </div>

              <div className="space-y-1.5">
                <label className="text-xs font-semibold text-zinc-600 dark:text-zinc-400 uppercase tracking-wider">
                  Backend Framework & Database
                </label>
                <select
                  value={backendStack}
                  onChange={(e) => setBackendStack(e.target.value)}
                  className="w-full bg-zinc-50 dark:bg-zinc-950 border border-zinc-200 dark:border-zinc-800 rounded-lg p-2 text-xs text-zinc-800 dark:text-zinc-200 font-medium"
                >
                  <option value="nodejs">Node.js (NestJS / Fastify) + PostgreSQL</option>
                  <option value="python">Python (FastAPI / Celery) + PostgreSQL</option>
                  <option value="go">Go (Gin / GORM) + PostgreSQL</option>
                  <option value="supabase">Supabase (PostgreSQL + RLS + Edge Functions)</option>
                  <option value="dotnet">.NET 9 (C#) + SQL Server</option>
                </select>
              </div>
            </div>
          </Card>

          {/* Navigation Action */}
          <div className="flex items-center justify-between pt-2">
            <Button
              variant="outline"
              size="md"
              onClick={() => setCurrentStep(1)}
              className="text-xs"
            >
              Back to Brief
            </Button>

            <Button
              variant="glow"
              size="lg"
              onClick={() => setCurrentStep(3)}
              className="gap-2 px-7 font-bold shadow-lg"
            >
              <Sparkles className="w-4 h-4" />
              <span>Launch AI Intelligence Extraction</span>
            </Button>
          </div>
        </div>
      )}

      {/* ================= STEP 3: PROCESSING STAGE ================= */}
      {currentStep === 3 && (
        <div className="max-w-2xl mx-auto py-8 space-y-8">
          <div className="text-center space-y-2">
            <div className="w-16 h-16 rounded-3xl bg-gradient-to-tr from-sky-500 to-indigo-600 flex items-center justify-center text-white mx-auto shadow-lg shadow-sky-500/20 animate-pulse">
              <Cpu className="w-8 h-8 animate-spin" style={{ animationDuration: "6s" }} />
            </div>
            <h2 className="text-xl font-bold text-zinc-900 dark:text-zinc-100">
              AI Intelligence Pipeline Executing
            </h2>
            <p className="text-xs text-zinc-500 dark:text-zinc-400">
              Parsing client brief with Groq enterprise reasoning model...
            </p>
          </div>

          {/* Progress Bar Card */}
          <Card className="bg-white dark:bg-zinc-900/80 border-zinc-200 dark:border-zinc-800 p-6 space-y-6 shadow-md">
            <div className="space-y-2">
              <div className="flex items-center justify-between text-xs font-semibold">
                <span className="text-sky-700 dark:text-sky-300 font-mono">
                  {stages[currentProcessStage] || stages[0]}
                </span>
                <span className="font-mono text-zinc-600 dark:text-zinc-400">{progressPercent}%</span>
              </div>
              <div className="w-full h-2.5 bg-zinc-100 dark:bg-zinc-800 rounded-full overflow-hidden">
                <div
                  className="h-full bg-gradient-to-r from-sky-500 via-indigo-500 to-emerald-500 rounded-full transition-all duration-500 ease-out"
                  style={{ width: `${progressPercent}%` }}
                />
              </div>
            </div>

            {/* Checklist of stages */}
            <div className="space-y-2.5 pt-2 border-t border-zinc-100 dark:border-zinc-800">
              {stages.map((stage, idx) => {
                const isDone = currentProcessStage > idx || progressPercent === 100;
                const isCurrent = currentProcessStage === idx && progressPercent < 100;
                return (
                  <div
                    key={idx}
                    className={cn(
                      "flex items-center gap-3 text-xs transition-colors p-2 rounded-lg",
                      isDone
                        ? "text-emerald-700 dark:text-emerald-400 bg-emerald-50/50 dark:bg-emerald-950/20"
                        : isCurrent
                        ? "text-sky-700 dark:text-sky-300 font-semibold bg-sky-50/50 dark:bg-sky-950/30"
                        : "text-zinc-400 dark:text-zinc-600"
                    )}
                  >
                    {isDone ? (
                      <CheckCircle2 className="w-4 h-4 text-emerald-500 shrink-0" />
                    ) : isCurrent ? (
                      <div className="w-4 h-4 border-2 border-sky-500 border-t-transparent rounded-full animate-spin shrink-0" />
                    ) : (
                      <div className="w-4 h-4 rounded-full border border-zinc-300 dark:border-zinc-700 shrink-0" />
                    )}
                    <span>{stage}</span>
                  </div>
                );
              })}
            </div>
          </Card>
        </div>
      )}
    </div>
  );
}
