"use client";

import React, { useState } from "react";
import { Copy, Check, Download, FileText, CheckCircle2, Share2, Layers, Code } from "lucide-react";
import { Button, Card } from "@/lib/ui-index";
import { Project, Requirement, MermaidDiagramData } from "@/lib/types";
import { useToast } from "@/components/ui/Toast";
import { cn } from "@/lib/utils";

interface ExportPanelProps {
  project: Project;
  requirements: Requirement[];
  diagrams: MermaidDiagramData[];
}

export function ExportPanel({ project, requirements, diagrams }: ExportPanelProps) {
  const { success } = useToast();
  const [selectedFormat, setSelectedFormat] = useState<"prd_markdown" | "client_pdf" | "jira_csv" | "openapi">("prd_markdown");
  const [copied, setCopied] = useState<boolean>(false);

  // Generate Markdown PRD
  const markdownContent = `# Product Requirement Document (PRD): ${project.name}
**Client:** ${project.clientName}
**Version:** ${project.currentVersion} (${project.status})
**Date:** ${new Date().toLocaleDateString()}
**Platform:** ${project.platform}

---

## 1. Executive Summary
${project.executiveSummary}

### 1.1 Business Scope Objectives
${project.scopeObjectives.map((obj) => `- ${obj}`).join("\n")}

### 1.2 Explicitly Out of Scope
${project.outOfScope.map((obj) => `- ${obj}`).join("\n")}

---

## 2. Technical Stack & Architecture
- **Frontend / Client:** ${project.techStack.frontend}
- **Backend Services:** ${project.techStack.backend}
- **Database:** ${project.techStack.database}
- **Hosting / Cloud:** ${project.techStack.hosting}
- **Pattern:** ${project.techStack.architecture}

---

## 3. Requirement Specification Matrix (${requirements.length} Items)

${requirements
  .map(
    (req) => `### [${req.code}] ${req.title}
- **Type:** ${req.type} | **Priority:** ${req.priority} | **Status:** ${req.status}
- **Category:** ${req.category}
- **Effort Estimate:** ${req.estimatedHours} hours (${req.storyPoints} pts)
- **Source Citation:** *${req.sourceExcerpt.documentName} (p.${req.sourceExcerpt.pageNumber}, para ${req.sourceExcerpt.paragraphNumber})*
> "${req.sourceExcerpt.text}"

**Specification:**
${req.description}

**Acceptance Criteria:**
${req.acceptanceCriteria
  .map(
    (ac, idx) => `*Scenario ${idx + 1}:*
- **Given** ${ac.given}
- **When** ${ac.when}
- **Then** ${ac.then}`
  )
  .join("\n")}

${req.technicalNotes ? `**Technical Implementation Notes:**\n\`${req.technicalNotes}\`\n` : ""}
---`
  )
  .join("\n\n")}

---

## 4. Architectural & Sequence Diagrams

${diagrams
  .map(
    (diag) => `### 4.${diag.type} - ${diag.title}
\`\`\`mermaid
${diag.code}
\`\`\`
`
  )
  .join("\n")}

---
*Generated by SpecGuard AI Requirement Intelligence Platform*
`;

  // Generate Jira CSV Format
  const jiraCsvContent = `Issue Type,Summary,Description,Priority,Epic Link,Story Points,Custom Field (Source Citation)
${requirements
  .map(
    (r) =>
      `"Story","[${r.code}] ${r.title.replace(/"/g, '""')}","${r.description.replace(/"/g, '""')}","${r.priority}","${r.category}","${r.storyPoints}","${r.sourceExcerpt.documentName} p.${r.sourceExcerpt.pageNumber}"`
  )
  .join("\n")}`;

  // Generate OpenAPI Draft
  const openApiContent = `openapi: 3.0.3
info:
  title: ${project.name} API
  version: 1.0.0
  description: Automatically scaffolded from SpecGuard requirement extraction.
paths:
  /auth/passkey-biometric:
    post:
      summary: REQ-AUTH-01 Biometric & Passkey validation
      responses:
        '200':
          description: Authenticated token response
  /wallets/transfer:
    post:
      summary: REQ-SEC-01 Instant Idempotent P2P Transfer
      parameters:
        - in: header
          name: Idempotency-Key
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Transfer settled receipt
  /escrow/milestones:
    post:
      summary: REQ-ESCROW-01 Milestone Escrow Agreement
      responses:
        '201':
          description: Escrow agreement created`;

  const activeContent =
    selectedFormat === "prd_markdown" || selectedFormat === "client_pdf"
      ? markdownContent
      : selectedFormat === "jira_csv"
      ? jiraCsvContent
      : openApiContent;

  const handleCopy = async () => {
    await navigator.clipboard.writeText(activeContent);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
    success("Copied to Clipboard", "Export content copied successfully.");
  };

  const handleDownload = () => {
    const ext = selectedFormat === "jira_csv" ? "csv" : selectedFormat === "openapi" ? "yaml" : "md";
    const blob = new Blob([activeContent], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${project.name.toLowerCase().replace(/[^a-z0-9]/g, "-")}-spec.${ext}`;
    a.click();
    URL.revokeObjectURL(url);
    success("Export File Downloaded", `Downloaded ${ext.toUpperCase()} spec blueprint.`);
  };

  return (
    <div className="space-y-6">
      {/* Format Selector Bar */}
      <div className="flex flex-wrap items-center justify-between gap-3 bg-white dark:bg-zinc-900/60 p-4 rounded-xl border border-zinc-200 dark:border-zinc-800 shadow-xs">
        <div className="flex items-center gap-2">
          {[
            { id: "prd_markdown", label: "Full PRD Markdown", icon: <FileText className="w-3.5 h-3.5" /> },
            { id: "client_pdf", label: "Client Sign-Off Spec", icon: <CheckCircle2 className="w-3.5 h-3.5" /> },
            { id: "jira_csv", label: "Jira / Linear CSV", icon: <Layers className="w-3.5 h-3.5" /> },
            { id: "openapi", label: "OpenAPI YAML Draft", icon: <Code className="w-3.5 h-3.5" /> },
          ].map((fmt) => (
            <button
              key={fmt.id}
              onClick={() => setSelectedFormat(fmt.id as any)}
              className={cn(
                "px-3 py-1.5 rounded-lg text-xs font-semibold transition-colors flex items-center gap-1.5",
                selectedFormat === fmt.id
                  ? "bg-sky-50 dark:bg-sky-950/80 text-sky-700 dark:text-sky-400 border border-sky-200 dark:border-sky-800/60"
                  : "text-zinc-600 dark:text-zinc-400 hover:text-zinc-900 dark:hover:text-zinc-200"
              )}
            >
              {fmt.icon}
              <span>{fmt.label}</span>
            </button>
          ))}
        </div>

        <div className="flex items-center gap-2">
          <Button variant="secondary" size="sm" onClick={handleDownload}>
            <Download className="w-3.5 h-3.5" />
            <span>Download</span>
          </Button>
          <Button variant="glow" size="sm" onClick={handleCopy}>
            {copied ? (
              <>
                <Check className="w-3.5 h-3.5 text-emerald-600 dark:text-emerald-300" />
                <span>Copied</span>
              </>
            ) : (
              <>
                <Copy className="w-3.5 h-3.5" />
                <span>Copy Export</span>
              </>
            )}
          </Button>
        </div>
      </div>

      {/* Code / Markdown Preview Area */}
      <div className="rounded-xl border border-zinc-200 dark:border-zinc-800 bg-zinc-900 text-zinc-100 p-6 overflow-hidden shadow-xs">
        <pre className="text-xs font-mono text-zinc-200 leading-relaxed max-h-[580px] overflow-y-auto whitespace-pre-wrap select-all">
          {activeContent}
        </pre>
      </div>
    </div>
  );
}
